import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * 1700000000005-HardenCashDrawerBranchFK
 *
 * Phase 3 — Foreign Key Hardening
 *
 * Problem:
 *   cash_drawers.branch_id was created with ON DELETE CASCADE (init.sql line 594).
 *   That means deleting a branch silently deletes every cash drawer for that
 *   branch — including open drawers with live balances — without any warning.
 *   This is a silent data-destruction risk.
 *
 * Fix:
 *   Drop the existing CASCADE constraint and re-create it as ON DELETE RESTRICT.
 *   A branch with drawers can no longer be deleted until those drawers are
 *   closed/archived first, which is the correct business rule.
 *
 * Rollback (down()):
 *   Restores the original CASCADE behaviour. Run only if you need to undo this.
 *
 * Prerequisites:
 *   cash_drawers table exists (FoundationSchema1700000000001 applied).
 *
 * Safe to run on live DB:
 *   Dropping and recreating a FK constraint acquires only a brief metadata lock
 *   (no table rewrite). No data is modified.
 */
export class HardenCashDrawerBranchFK1700000000005 implements MigrationInterface {
  name = 'HardenCashDrawerBranchFK1700000000005';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Step 1 — Find the real constraint name (auto-generated by PostgreSQL when
    // the table was created inline, so the name is not deterministic).
    // We query information_schema to avoid hard-coding a name that may differ
    // between environments.
    const rows: Array<{ constraint_name: string }> = await queryRunner.query(`
      SELECT tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.constraint_column_usage ccu
             ON tc.constraint_name = ccu.constraint_name
            AND tc.table_schema    = ccu.table_schema
       WHERE tc.constraint_type = 'FOREIGN KEY'
         AND tc.table_name      = 'cash_drawers'
         AND ccu.column_name    = 'branch_id'
         AND tc.table_schema    = 'public'
       LIMIT 1;
    `);

    if (rows.length === 0) {
      // No branch FK exists on cash_drawers — nothing to change.
      // This can happen if the table was created without one (nullable branch_id
      // added inline without an explicit FK). Log and exit gracefully.
      console.warn(
        '[HardenCashDrawerBranchFK] No branch_id FK found on cash_drawers — skipping drop.',
      );
    } else {
      const constraintName = rows[0].constraint_name;

      // Step 2 — Drop the old CASCADE constraint.
      await queryRunner.query(
        `ALTER TABLE cash_drawers DROP CONSTRAINT IF EXISTS "${constraintName}";`,
      );
    }

    // Step 3 — Add the hardened RESTRICT constraint under a deterministic name.
    // Using IF NOT EXISTS via a DO block so the migration is idempotent.
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1
            FROM information_schema.table_constraints
           WHERE constraint_name = 'fk_cash_drawers_branch_restrict'
             AND table_name      = 'cash_drawers'
             AND table_schema    = 'public'
        ) THEN
          ALTER TABLE cash_drawers
            ADD CONSTRAINT fk_cash_drawers_branch_restrict
            FOREIGN KEY (branch_id)
            REFERENCES branches(id)
            ON DELETE RESTRICT;
        END IF;
      END $$;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Restore the original CASCADE behaviour.
    await queryRunner.query(`
      ALTER TABLE cash_drawers
        DROP CONSTRAINT IF EXISTS fk_cash_drawers_branch_restrict;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1
            FROM information_schema.table_constraints
           WHERE constraint_name = 'fk_cash_drawers_branch_cascade'
             AND table_name      = 'cash_drawers'
             AND table_schema    = 'public'
        ) THEN
          ALTER TABLE cash_drawers
            ADD CONSTRAINT fk_cash_drawers_branch_cascade
            FOREIGN KEY (branch_id)
            REFERENCES branches(id)
            ON DELETE CASCADE;
        END IF;
      END $$;
    `);
  }
}
